#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTiONFvPD+fa86riRtuQtEoUMrpk83tf5xTT8E5Pz5JkS77aAAtP9PGSSIII3c8jPNrx5fL8fQq/1f5d8rWG841ofeRAVxK5VdPsdXnYiV4uLu4IrpuzN7x/F8hqPsMVrhbyKCwTRfUfDUfLOzKFsizHFxVXiR2xvq9EhulYMNBv9MM1DXMINr46eTmcI8ygQcGgWTHZ2vpO6QNf7M2MLXCBBJgZS1KLnEqnsS8uLU823W28Cn9GL+xdT5GStygz5FqxI+AlyLwNBKrzQ+QHo6vaFskd0X1wzraYKdizCqNzZgZgagCwS/tgU1cMHEU94ou8JIMwPIm0rBpTcSEelZ aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key

ssh_pwauth: false
disable_root: false 
package_update: true
packages:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysql
  - adminer

write_files:
  - path: /var/www/html/info.php
    content: |
      <?php phpinfo(); ?>

   - path: /var/www/html/db.php
    content: |
      <?php
      $servername = "172.31.25.112";
      $username = "admin";
      $password = "AWSadmin2209";
      $dbname = "mysql";
      $conn = new mysqli($servername, $username, $password, $dbname);
      if ($conn->connect_error) { die("Connection failed: " . $conn->connect_error); }
      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
        echo("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
      }
      ?>

runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
