#cloud-config
users: 
  - name: ubuntu 
    sudo: ALL=(ALL) NOPASSWD:ALL 
    groups: users, admin 
    home: /home/ubuntu 
    shell: /bin/bash 
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTs0haa/p1gU01Nr0ZbzhsrC2WRzFt4HCrywFLxncoTzBxJlU5MBSGkZUv2yzjkEoFHpNtRCz5ofvZAkYivKdk9p/8m6nYWGIGHa9gmOSG9/VKbF8NaGPaevwFzo42C+ciB/7Xu8BWxwk6JygJWR2ZCxZSMt8S3AFaoUztWxD7xIvfGvwbaaNskKi3LXbNVcRC+wefOvM3hbjufXoDkveswEgLYWgIccfENMXO/z+VYW1Bu+OPD7YiACT6W6qGakMnHCuO9CQJZXGyaiWVB3Fh9Wwp3he7o0VGc2YHjSU4gzP6K08X480bYmlDIdLgNDLsojjw9Y1TARPu6jiQdGpP aws-key-jev 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key-NUY

ssh_pwauth: false
disable_root: true

package_update: true
packages:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer

write_files:
  - path: /var/www/html/info.php
    content: |
      <?php phpinfo(); ?>

  - path: /var/www/html/db.php
    content: |
      <?php
      $servername = "172.31.25.112";
      $username = "admin";
      $password = "AWSadmin2209";
      $dbname = "mysql";
      $conn = new mysqli($servername, $username, $password, $dbname);
      if ($conn->connect_error) { die("Connection failed: " . $conn->connect_error); }
      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
        echo("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
      }
      ?>

runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
