#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTiONFvPD+fa86riRtuQtEoUMrpk83tf5xTT8E5Pz5JkS77aAAtP9PGSSIII3c8jPNrx5fL8fQq/1f5d8rWG841ofeRAVxK5VdPsdXnYiV4uLu4IrpuzN7x/F8hqPsMVrhbyKCwTRfUfDUfLOzKFsizHFxVXiR2xvq9EhulYMNBv9MM1DXMINr46eTmcI8ygQcGgWTHZ2vpO6QNf7M2MLXCBBJgZS1KLnEqnsS8uLU823W28Cn9GL+xdT5GStygz5FqxI+AlyLwNBKrzQ+QHo6vaFskd0X1wzraYKdizCqNzZgZgagCwS/tgU1cMHEU94ou8JIMwPIm0rBpTcSEelZ aws-key       
ssh_pwauth: false
disable_root: false 
package_update: true
packages:
  - curl 
  - wget 
